import pandas as pd

produtos = [
    ("ABEV3.SA","Espada de Fogo", "Uma espada encantada que inflama ao comando."),
    ("AZUL4.SA","Armadura Etérea", "Armadura leve que oferece proteção contra ataques espirituais."),
    ("B3SA3.SA","Pergaminho do Dragão", "Contém um feitiço poderoso, ainda indecifrado."),
    ("BBAS3.SA","Poção de Cura", "Restaura pequenas quantidades de pontos de vida."),
    ("BBDC3.SA","Anel de Invisibilidade", "Torne-se invisível por curtos períodos."),
    ("BBDC4.SA","Elmo do Falcão", "Melhora a visão e percepção do usuário."),
    ("BBSE3.SA","Botas Aladas", "Permite ao usuário levitar por curtos períodos."),
    ("BRAP4.SA","Amuleto da Sorte", "Aumenta a chance de acertos críticos."),
    ("BRFS3.SA","Manto das Sombras", "Concede habilidades de furtividade."),
    ("BRKM5.SA","Lança Relâmpago", "Pode eletrocutar inimigos ao contato."),
    ("CCRO3.SA","Escudo de Gaia", "Um escudo que absorve ataques mágicos."),
    ("CIEL3.SA","Dardo Encantado", "Nunca erra o alvo."),
    ("CMIG4.SA","Baú do Ladrão", "Pequeno baú que pode conter itens valiosos."),
    ("COGN3.SA","Cetro Lunar", "Amplifica habilidades mágicas relacionadas à lua."),
    ("CSAN3.SA","Tomo dos Mortos", "Permite ao usuário comunicar-se com espíritos."),
    ("CSNA3.SA","Bálsamo Restaurador", "Cura doenças e venenos."),
    ("CVCB3.SA","Arco Solar", "Seus tiros são feitos de pura luz."),
    ("CYRE3.SA","Diadema de Sereia", "Permite respirar debaixo d'água."),
    ("ECOR3.SA","Manoplas do Ogro", "Aumenta a força física do usuário."),
    ("EGIE3.SA","Bastão de Oráculo", "Revela o futuro próximo."),
    ("ELET3.SA","Pedra Telepática", "Permite comunicação mental."),
    ("ELET6.SA","Máscara da Noite", "Concede visão noturna."),
    ("EMBR3.SA","Flauta Hipnótica", "Pode colocar inimigos em transe."),
    ("ENBR3.SA","Capa de Voo", "Permite ao usuário voar."),
    ("EQTL3.SA","Frasco de Névoa", "Libera uma névoa densa para fuga rápida."),
    ("FLRY3.SA","Grimório Elemental", "Livro de feitiços de elementais."),
    ("GGBR4.SA","Adaga do Assassino", "Extremamente afiada e quase indetectável."),
    ("GOAU4.SA","Bola de Cristal", "Usada para espiar lugares distantes."),
    ("GOLL4.SA","Cordão do Tempo", "Pode retardar ou acelerar o tempo ao redor do usuário."),
    ("HYPE3.SA","Bracelete de Gelo", "Concede resistência ao frio e pode congelar inimigos."),
    ("IRBR3.SA","Tocha Eterna", "Uma tocha que nunca se apaga."),
    ("ITSA4.SA","Moeda da Fortuna", "Decide o resultado de uma escolha ao ser lançada."),
    ("ITUB4.SA","Pena de Grifo", "Usada para escrever contratos mágicos."),
    ("JBSS3.SA","Relicário da Vida", "Pode reviver uma pessoa uma única vez."),
    ("KLBN11.SA","Broche de Fala", "Permite falar e compreender qualquer língua."),
    ("LREN3.SA","Bainha Mágica", "Qualquer espada colocada se torna afiada e encantada."),
    ("MGLU3.SA","Pederneira de Fênix", "Cria fogo que nunca se extingue."),
    ("MRFG3.SA","Tiara da Sabedoria", "Aumenta a inteligência e conhecimento do usuário."),
    ("MRVE3.SA","Óleo de Hermes", "Acelera objetos quando aplicado."),
    ("MULT3.SA","Talismã do Retorno", "Teleporta o usuário para um local pré-determinado."),
    ("NTCO3.SA","Selo do Silêncio", "Previne magias de serem lançadas nas proximidades."),
    ("PCAR3.SA","Colar da Resistência", "Protege contra maldições e encantamentos."),
    ("PETR3.SA","Harpa Celestial", "Sons podem curar feridas e acalmar corações."),
    ("PETR4.SA","Frasco de Vento", "Libera fortes rajadas de vento."),
    ("QUAL3.SA","Pergaminho Vazio", "Pode armazenar qualquer feitiço escrito nele."),
    ("RADL3.SA","Sino do Acordar", "Desperta qualquer um de um sono profundo."),
    ("RENT3.SA","Corda Infinita", "Estende-se tanto quanto o usuário precisar."),
    ("SANB11.SA","Cajado de Energia", "Amplifica feitiços de ataque do usuário."),
    ("SBSP3.SA","Anel de Teleporte", "Teleporta o usuário para locais conhecidos."),
    ("SUZB3.SA","Flecha Fantasma", "Passa através de objetos sólidos."),
    ("TAEE11.SA","Varinha da Ilusão", "Cria ilusões realísticas."),
    ("TOTS3.SA","Martelo de Eco", "Produz um som ensurdecedor ao atingir."),
    ("UGPA3.SA","Cinto de Levitação", "Eleva o usuário acima do solo."),
    ("USIM5.SA","Botas do Deserto", "Previne exaustão em climas quentes."),
    ("VALE3.SA","Garrafa de Tempestade", "Pode convocar uma tempestade quando aberta."),
    ("VIVT3.SA","Espelho de Verdade", "Revela a verdadeira forma de qualquer um refletido nele."),
    ("WEGE3.SA","Lira de Encantamento", "Encanta quem ouve sua melodia."),
    ("YDUQ3.SA","Máscara do Medo", "Induz terror em quem a observa.")
]

df_produtos = pd.DataFrame(produtos, columns=['des_ticket_price', 'nom_produto','des_produto'])